### ISSUE TITLE
Rule 1635 not working.

### ISSUE THREAD

**Issue by bwanab** [MartinuzziFrancesco/CellularAutomata.jl#11]
Hi. Great library, but when I copy/paste your code for Totalistic Cellular Automata rule 1635, I am getting what looks like a straight line. Installed using Pkg.add("CellularAutomata").

The Elementary and General CA examples all worked as advertised.

The version of julia is 1.9.3 if that helps.

**Comment by MartinuzziFrancesco** [comment]
Hi! Thanks, and sorry for not replying sooner! The error apparently is just in the readme, it should be `ca = CellularAutomaton(TCA(rule, states=states), starting_val, generations)` instaed of `ca = CellularAutomaton(DCA(rule, states=states), starting_val, generations)`
