### ISSUE TITLE
Great package!

### ISSUE THREAD

**Issue by cormullion** [MartinuzziFrancesco/CellularAutomata.jl#2]
No issue - just wanted to say I like the package and I'm enjoying exploring the many possibilities. I haven't read the Wolfram book (and not sure I will 😄), so I'm looking forward to reading your documentation. Here's a screenshot of what I'm currently looking at:

<img width="494" alt="Screenshot 2021-10-23 at 13 33 02" src="https://user-images.githubusercontent.com/52289/138556460-8ac71d1a-36d8-410e-9885-ce9375b0e008.png">

I'm not quite sure how `rule = 0.9159655941772` generates it yet, but there's a lot to explore.

Thanks!

**Comment by MartinuzziFrancesco** [comment]
This issue must have slipped through the notifications, sorry for not getting back sooner! Thanks for the kind words! 

yeha reading the full Wolfram book end to end is really not doable honestly, but there is plenty of interesting stuff if you find the time to look for it. 

That rule really does look strange, good catch!

**Comment by MartinuzziFrancesco** [comment]
some (very primitive) docs are finally [online](https://martinuzzifrancesco.github.io/CellularAutomata.jl/dev/)!
